apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-service
  template:
    metadata:
      labels:
        app: market-service
    spec:
      containers:
        - name: market-service
          image: your-registry/market-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: ENV
              value: "dev"
---
apiVersion: v1
kind: Service
metadata:
  name: market-service
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: market-service
