"""add account_number to users

Revision ID: 5f6e1d963c95
Revises: 8a9349a358d6
Create Date: 2026-07-01 14:23:05.318797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6e1d963c95'
down_revision: Union[str, None] = '8a9349a358d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_account_number'), ['account_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_account_number'))
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
