"""rbac and maker checker

Revision ID: 8e7758e3900a
Revises: f3c6271c9a23
Create Date: 2026-06-06 01:16:53.853601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7758e3900a'
down_revision: Union[str, None] = 'f3c6271c9a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_features_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_name'), ['name'], unique=True)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tiers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tiers_name'), ['name'], unique=True)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('tier_features',
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tier_id', 'feature_id')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('maker_id', sa.Integer(), nullable=False),
    sa.Column('checker_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('actioned_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['checker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_id'), ['id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_tier_id', 'tiers', ['tier_id'], ['id'])

    # --- SEED & DATA MIGRATION CODE ---
    permissions_table = sa.table('permissions',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('description', sa.String)
    )
    op.bulk_insert(permissions_table, [
        {'id': 1, 'name': 'manage_tiers', 'description': 'Create and edit custom tiers and features checklist'},
        {'id': 2, 'name': 'make_request', 'description': 'Create maker-checker requests'},
        {'id': 3, 'name': 'approve_request', 'description': 'Approve maker-checker requests'},
    ])

    roles_table = sa.table('roles',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('description', sa.String)
    )
    op.bulk_insert(roles_table, [
        {'id': 1, 'name': 'Admin', 'description': 'Super Administrator - Bypass Maker-Checker approvals'},
        {'id': 2, 'name': 'Maker Admin', 'description': 'Maker Administrator - Can create requests'},
        {'id': 3, 'name': 'Checker Admin', 'description': 'Checker Administrator - Can approve requests'},
        {'id': 4, 'name': 'Regular User', 'description': 'Regular trading user'},
    ])

    role_permissions_table = sa.table('role_permissions',
        sa.column('role_id', sa.Integer),
        sa.column('permission_id', sa.Integer)
    )
    op.bulk_insert(role_permissions_table, [
        {'role_id': 2, 'permission_id': 2},
        {'role_id': 3, 'permission_id': 3},
        {'role_id': 1, 'permission_id': 1},
        {'role_id': 1, 'permission_id': 2},
        {'role_id': 1, 'permission_id': 3},
    ])

    features_table = sa.table('features',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('code', sa.String),
        sa.column('description', sa.String)
    )
    op.bulk_insert(features_table, [
        {'id': 1, 'name': 'Spot Market Watchlist', 'code': 'watchlist_access', 'description': 'Access basic asset watchlist'},
        {'id': 2, 'name': 'Lightweight Charts', 'code': 'charts_access', 'description': 'View interactive TradingView charts'},
        {'id': 3, 'name': 'Priority WebSocket Stream', 'code': 'priority_websockets', 'description': 'Access fast WebSocket connections'},
        {'id': 4, 'name': 'KYC Check Gateway', 'code': 'kyc_gateway', 'description': 'Validate registration via KYC'},
        {'id': 5, 'name': 'AML Compliance Gateway', 'code': 'aml_gateway', 'description': 'Pass automated AML compliance checks'},
    ])

    tiers_table = sa.table('tiers',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('price', sa.Float),
        sa.column('description', sa.String)
    )
    op.bulk_insert(tiers_table, [
        {'id': 1, 'name': 'Starter', 'price': 0.0, 'description': 'Standard basic free tier'},
        {'id': 2, 'name': 'Standard', 'price': 19.0, 'description': 'Advanced analytics standard tier'},
        {'id': 3, 'name': 'Premium', 'price': 49.0, 'description': 'Elite trading premium tier'},
    ])

    tier_features_table = sa.table('tier_features',
        sa.column('tier_id', sa.Integer),
        sa.column('feature_id', sa.Integer)
    )
    op.bulk_insert(tier_features_table, [
        {'tier_id': 1, 'feature_id': 1},
        {'tier_id': 1, 'feature_id': 2},
        {'tier_id': 2, 'feature_id': 1},
        {'tier_id': 2, 'feature_id': 2},
        {'tier_id': 2, 'feature_id': 3},
        {'tier_id': 2, 'feature_id': 4},
        {'tier_id': 3, 'feature_id': 1},
        {'tier_id': 3, 'feature_id': 2},
        {'tier_id': 3, 'feature_id': 3},
        {'tier_id': 3, 'feature_id': 4},
        {'tier_id': 3, 'feature_id': 5},
    ])

    op.execute("UPDATE users SET tier_id = 1 WHERE tier = 'starter'")
    op.execute("UPDATE users SET tier_id = 2 WHERE tier = 'standard'")
    op.execute("UPDATE users SET tier_id = 3 WHERE tier = 'premium'")

    op.execute("INSERT INTO user_roles (user_id, role_id) SELECT id, 1 FROM users WHERE role = 'admin'")
    op.execute("INSERT INTO user_roles (user_id, role_id) SELECT id, 2 FROM users WHERE role = 'admin'")
    op.execute("INSERT INTO user_roles (user_id, role_id) SELECT id, 3 FROM users WHERE role = 'admin'")
    op.execute("INSERT INTO user_roles (user_id, role_id) SELECT id, 4 FROM users WHERE role = 'user'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tier_id')

    op.drop_table('user_roles')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_id'))

    op.drop_table('approval_requests')
    op.drop_table('tier_features')
    op.drop_table('role_permissions')
    with op.batch_alter_table('tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tiers_name'))
        batch_op.drop_index(batch_op.f('ix_tiers_id'))

    op.drop_table('tiers')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.drop_index(batch_op.f('ix_permissions_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_name'))
        batch_op.drop_index(batch_op.f('ix_features_id'))
        batch_op.drop_index(batch_op.f('ix_features_code'))

    op.drop_table('features')
    # ### end Alembic commands ###
